No estoy segura de dónde debo subirla
eslibre/charlas pull request #15
Opened 2019-03-31 22:05 UTC by LastStrawberry

# Social justice code repositories

¿Garantiza el software libre que el usuario sea libre? ¿Son necesarios y suficientes los principios del FSM para garantizar la justicia? ¿Cuál es el rol de los repositorios de código en la promoción de la justicia en el software? Estas son algunas de las preguntas que intentaremos desgranar con el propósito principal de analizar bajo qué condiciones el Free Software Movement funciona para alcanzar la justicia en la producción, uso y consumo de software. Así, la base de la charla será retar el funcionamiento de las tesis de Richard Stallman como teoría, poniendo en valor el rol de los repositorios de código abierto y buscando los puntos débiles que deben ser mejorados.

Si bien la charla presenta un punto de vista teórico, pretende ponerle sentido al FSM a través de diferentes teorías de la justicia demostrando cómo el FSM puede ser clave en la libertad del usuario sin quedarse en papel mojado.

(Charla 50 min)

# Lorena Sánchez Chamorro

Jurista y politóloga. MSc Media and Communications Governance en London School of Economics. Master en Derecho Tecnológico e Informática Forense. Consultora de seguridad, riesgos tecnológicos y legaltech, e investigadora independiente en tecnologías y el impacto que tienen en el derecho, ciencias políticas y seguridad internacional. También es editora del medio de análisis político y social Polikracia. Está especializada en derecho tecnológico, protección de datos, seguridad informática y su relación con las ciencias sociales.

# Condiciones

* [ ] Acepto seguir el [código de conducta](https://eslib.re/2019/conducta/) y solicitar a los asistentes y ponentes esta aceptación.
* [ ] Al menos una persona entre los que la proponen estará presente en Granada el día 21 junio de 2019.

2019-04-01 06:46 UTC, acs commented
Ponencia muy en la línea de la temática del congreso sobre los principios del software libre. Encuentro especialmente interesante lo de retar los principios del software libre, con algo empírico como son los repositorios de software, y un marco teórico (teorías de la justicia) con el que comparar. Sería útil saber que teorías en concreto se utilizarán para la comparativa, pero yo ya lo encuentro lo suficientemente interesante como para darle un +1 viendo el perfil de la autora y de un vistazo rápido a https://polikracia.com/.

2019-04-01 07:22 UTC, JJ requested changes
El tema de la charla lo veo genial, pero sería mucho mejor que lo incluyeras en el otro fichero, [propuestas](https://github.com/eslibre/charlas/blob/master/propuestas/README.md), creo que encaja mucho mejor ahí.

2019-04-02 08:52 UTC, JJ approved these changes
En realidad está aprobada. Gracias.

2019-04-02 08:52 UTC, germaaan approved these changes
La temática es interesante y le puede dar más diversidad al evento. 👍

2019-04-02 09:07 UTC, terceranexus6 approved these changes
Creo que le puede dar un toque multidisciplinar al evento y además es una reflexión interesante que viene muy a cuento con el evento.

2019-04-02 09:08 UTC, merged

2019-04-02 09:08 UTC, germaaan commented
Tres revisiones positivas, así que propuesta aceptada. Gracias!

2019-04-02 17:26 UTC, LastStrawberry commented
¡Muchas gracias a todos! Y reitero mis disculpas por mi escaso conocimiento en Github y las molestias ocasionadas ^^ ¡Saludos!