propuesta de charla: flying to the cloud
eslibre/charlas pull request #32
Opened 2019-05-06 14:34 UTC by pplu

# Nombre de la propuesta

# Se trata de una

* [x] Charla/tutorial/charla relámpago

# Personas que la proponen

Jose Luis Martinez Torres (@pplu)

# Condiciones

* [ ] *[Sólo para devrooms]* Acepto coordinarme con la organización de esLibre.
* [ ] *[Sólo para devrooms]* Entiendo que si no hay un programa terminado para la fecha que establezca la organización, la *devroom* podría retirarse.
* [x] Acepto seguir el [código de conducta](https://eslib.re/2019/conducta/) y solicitar a los asistentes y ponentes esta aceptación.
* [x] Al menos una persona entre los que la proponen estará presente en Granada el día 21 junio de 2019.

2019-05-06 15:28 UTC, JJ requested changes
Sé que vas a hablar de temas de Perl y demás, pero deberías hacer un poco de énfasis en el hecho de que vas a hablar de software libre y cómo eso es el tema principal de la charla.

2019-05-09 09:00 UTC, pplu commented
La charla como tal no está centrada en software libre, sino que se centra en Cloud (hay alguna mención al software libre, por eso). Dada la cantidad de software libre que corre en cloud y que puedes hacer correr en el cloud. Se transmiten una serie de técnicas y consejos para cualquier lenguaje y/o tecnología. Creo que es interesante para la comunidad de desarrollo de software en general.

La charla del track de Perl es otra totalmente distinta.

2019-05-09 10:12 UTC, acs commented
Yo dependiendo de como esté orientada la charla le veo encaje o no ... podría ser interesante las implicaciones para el software libre de ejecutar en el cloud los servicios ... o como el software libre es la base de algunas de las ofertas de cloud (como Apache Airflow es la base de Google Composer ... ) pero si el punto de partida es presentar soluciones en el cloud y como se trabaja con ellas, no termino de ver el encaje.

2019-05-09 12:53 UTC, pplu commented
No se trata tanto de presentar soluciones cloud, sino de maneras nuevas de trabajar y diseñar software que se se pueden llevar a cabo gracias al cloud, sea cual sea el cloud que usas (elasticidad, tolerancia a fallos, autoreparación, inmutabilidad, infraestructura como código, blue / green deployments, etc). Puedo centrar el discurso alrededor de la containerización y de Kubernetes en vez de cloud, ya que lo mismo aplica en el caso de Kubernetes: ha hecho más facil que estos patrones se puedan llevar a cabo de manera neutral / portable entre distintos proveedores cloud con software Open Source. ¿Que os parece?

2019-05-09 13:04 UTC, acs commented
@pplu yo lo encuentro bien interesante, pero no está alineado con la temática del congreso IMHO. Vamos a ver que dice el resto. Gracias por el interés!

2019-06-01 13:41 UTC, germaaan commented
Ha habido algún cambio en esta charla entonces?

2019-06-03 09:40 UTC, frankiejol commented
Yo he visto ya esta charla, o al menos una versión, el año pasado y fué muy divertida e interesante. Pa ra mí un modelo de lo que tendrían que ser una charla en unas jornadas técnicas. Si sólo @pplu pudiera introducir algo más de software libre.

2019-06-03 12:36 UTC, pplu commented
@germaaan @frankiejol : como decía, puedo orientarlo a Kubernetes, que es open y permite implementar los patrones "cloud-friendly" mencionados, pero no he recibido mucho más feedback.

2019-06-03 12:43 UTC, acs commented
> @germaaan @frankiejol : como decía, puedo orientarlo a Kubernetes, que es open y permite implementar los patrones "cloud-friendly" mencionados, pero no he recibido mucho más feedback.

Para mi en este caso es un +1

2019-06-03 12:48 UTC, germaaan commented
Sí, perdona que se quedó algo colgado.

Pues si pudieras incluir eso en el archivo de la charla, yo creo que ya la podríamos dar todos por buena y aceptarla directamente. Gracias!

> @germaaan @frankiejol : como decía, puedo orientarlo a Kubernetes, que es open y permite implementar los patrones "cloud-friendly" mencionados, pero no he recibido mucho más feedback.

2019-06-03 13:20 UTC, pplu commented
@germaaan @acs : hecho

2019-06-03 13:22 UTC, germaaan approved these changes

2019-06-03 13:23 UTC, merged

2019-06-03 18:17 UTC, acs commented
La añado al listado de charlas aceptadas, que no se metió en este commit.