Propuesta de Charla: API Telegram + PHP
eslibre/charlas pull request #39
Opened 2019-05-30 08:31 UTC by IgnasiCR

Creación de propuesta de una charla para esLibre: API Telegram + PHP.

# API Telegram + PHP

# Se trata de una

* [ X] Charla/tutorial/charla relámpago
* [ ] Devroom

# Personas que la proponen

Ignasi Camacho Redo ([@IgnasiCR](https://github.com/IgnasiCR)), estudiante de Ingeniería Informática en la UGR y creador de ([@fightETSIIT_Bot](https://web.telegram.org/#/im?p=@FightETSIIT_Bot))

# Condiciones

* [ ] *[Sólo para devrooms]* Acepto coordinarme con la organización de esLibre.
* [ ] *[Sólo para devrooms]* Entiendo que si no hay un programa terminado para la fecha que establezca la organización, la *devroom* podría retirarse.
* [X] Acepto seguir el [código de conducta](https://eslib.re/2019/conducta/) y solicitar a los asistentes y ponentes esta aceptación.
* [X] Al menos una persona entre los que la proponen estará presente en Granada el día 21 junio de 2019.

2019-05-30 09:01 UTC, JJ requested changes
Imagino que has liberado el código del bot; si es así, te agradecería que lo incluyeras en la propuesta.

2019-05-30 09:06 UTC, IgnasiCR commented
Sí, el código está en GitHub desde este martes que fue cuando hice la presentación. Ahí he puesto el enlace al repositorio. Si quieres que mejor haga referencia a que está el código en un repositorio y no solo poner el enlace me lo dices.

2019-05-30 09:16 UTC, JJ approved these changes
En este caso, aprobado.

2019-06-01 13:42 UTC, germaaan approved these changes
Por mi parte bien.

2019-06-01 18:19 UTC, merged