Nos vemos en ESLIBRE, en cualquier caso :-)
eslibre/charlas pull request #41
Opened 2019-05-31 12:39 UTC by naldoco

# Nombre de la propuesta

# Se trata de una

* [ ] Charla/tutorial/charla relámpago
* [ ] Devroom

# Personas que la proponen

# Condiciones

* [ ] *[Sólo para devrooms]* Acepto coordinarme con la organización de esLibre.
* [ ] *[Sólo para devrooms]* Entiendo que si no hay un programa terminado para la fecha que establezca la organización, la *devroom* podría retirarse.
* [ ] Acepto seguir el [código de conducta](https://eslib.re/2019/conducta/) y solicitar a los asistentes y ponentes esta aceptación.
* [ ] Al menos una persona entre los que la proponen estará presente en Granada el día 21 junio de 2019.

2019-05-31 16:33 UTC, JJ approved these changes
Me parece buena idea.

2019-06-01 13:38 UTC, germaaan requested changes
Lo veo interesante, pero sería necesario indicar si es una charla larga o corta.

2019-06-02 07:21 UTC, acs commented
Para es un +1. Me interesa la programación funcional, y me gustan los enfoques prácticos y colaborativos para aprender a programar.

2019-06-02 10:45 UTC, naldoco commented
> Lo veo interesante, pero sería necesario indicar si es una charla larga o corta.

Es una charla larga, pero si es preciso, se puede adaptar a charla corta, evidentemente viendo menos.

2019-06-02 10:53 UTC, JJ commented
Por favor, modifícalo en el fichero.

2019-06-02 21:13 UTC, germaaan approved these changes
Perfecto, gracias por añadirlo!

2019-06-02 21:13 UTC, merged