dfurmans::ADT->Propuesta
eslibre/charlas pull request #43
Opened 2019-05-31 21:37 UTC by dfurmans

# Nombre de la propuesta

¿Porque tipos de datos algebraicos?
# Se trata de una

* [X] Charla/tutorial/charla relámpago
* [ ] Devroom

# Personas que la proponen
@dfurmans

# Condiciones

* [ ] *[Sólo para devrooms]* Acepto coordinarme con la organización de esLibre.
* [ ] *[Sólo para devrooms]* Entiendo que si no hay un programa terminado para la fecha que establezca la organización, la *devroom* podría retirarse.
* [X] Acepto seguir el [código de conducta](https://eslib.re/2019/conducta/) y solicitar a los asistentes y ponentes esta aceptación.
* [X] Al menos una persona entre los que la proponen estará presente en Granada el día 21 junio de 2019.

2019-06-01 07:14 UTC, JJ approved these changes
Voy a aprobar porque te conozco, pero el resto de los evaluadores no, así que sería conveniente que extendieras un poco más de qué vas a hablar y qué lenguajes vas a mencionar.

2019-06-01 13:45 UTC, germaaan requested changes
Opino lo mismo que @JJ, sé que tu charla será muy interesante, pero tanto para el resto de revisores como para los asistentes vendría mejor tener algo más de información.

Al menos por mi parte, en cuanto se resuelva eso, paso a +1 automáticamente.

2019-06-02 07:18 UTC, acs commented
Yo que no conozco al ponente, del resumen de la charla no tengo mucha idea de que podría ser sin tenerme que poner a investigar e intuir por donde pueden ir los tiros. Creo que hace falta detallar mejor el abstract para poder evaluar la charla.

2019-06-02 18:17 UTC, dfurmans commented
pues, la charla se trata sobre una introduccion a Type-Level Programming
En general quiería monstrar, presentar un par de cositas :
> ADT y algebra con Curry-Howard Isomorphism - una cosa que Philip Wadler (un co-autor de Generic in Java y claro un grande personaje dentro de mundo FP) - entonces eso sobre todo en Types Cardinalities 
> Pattern maching sobre ADT 
> Type Variance - en contexto del Functores  y sobre todo bifunctor y profunctores
> Ejemplos en Scala y Haskell y _
> Quíza un poco de kinds y type projector

Pues entonces resúmen :: Tiene pinta como una introduccion a Type Level

2019-06-02 18:39 UTC, JJ approved these changes
Ahora está un poco más claro.

2019-06-02 21:11 UTC, germaaan approved these changes

2019-06-02 21:12 UTC, merged