ML-y-DL.md
eslibre/charlas pull request #44
Opened 2019-06-01 12:39 UTC by luisgjaime

Nueva propuesta de charla de ML y DL

2019-06-01 13:47 UTC, germaaan reviewed
Yo la veo interesante, pero no sé si quizás cuadraría más en la devroom de Big Data y Machine Learning (https://github.com/acs/bigdata_ml_devroom).

Veamos qué opina el resto.

2019-06-01 13:50 UTC, germaaan requested changes
Por cierto, no me había dado cuenta, pero sería necesario que la solicitud siguiera la plantilla de solicitudes como el resto de PRs.

2019-06-02 07:16 UTC, acs commented
Yo veo interesante el tema, pero del resumen que se ha enviado, no veo de que va a ser la charla. Parece que es relacionado con buenas prácticas en Machine Learning, pero está muy poco definido. @luisgjaime podrías dar algo más de detalle? Y sí, podría cuadrar muy bien en la devroom de Big Data y Machine Learning en cuaquier caso. Quizá se podría hacer en el track principal la parte más genérica, y en la devroom entrar en todos los detalles.

2019-06-02 21:39 UTC, acs commented
Al final parece que no vamos a tener la devroom de big data y ml así que cuadra ya tal y como está presentada. A ver si el autor la amplia un poco más.

2019-06-03 09:02 UTC, luisgjaime commented
He procedido a hacer algunos de los cambios que solicitabais. 
La charla no estaría ligada a ninguna tecnología concreta. Aunque si hay ejemplos los haré en Python. 
Me gustaría puntualizar buenas prácticas a la hora de hacer ML o DL, y temas a la hora de preparar los datos que no se tienen en cuenta muchas veces. También cuando se quieren hacer comparaciones de experimentaciones. No sé si queda ahora algo más claro.

2019-06-03 09:05 UTC, acs commented
Para mi es un +1

2019-06-03 09:20 UTC, JJ requested changes
Aunque sabemos que la mayoría de las soluciones hoy en día están basadas en el software libre, querríamos que lo mencionaras explícitamente en la charla, ya que es el tema principal de la conferencia.

2019-06-03 10:07 UTC, JJ approved these changes
Mínimo cambio, pero suficiente :-)

2019-06-03 10:08 UTC, merged

2019-06-03 10:08 UTC, germaaan approved these changes
Todo correcto ya entonces.